unpackaged/main/default/objects/Library_Issue_Ret_Item__c/Library_Issue_Ret_Item__c.object-meta.xml
<CustomObject>
    <description>This Object is used to issue/return  Library Item(Books/)</description>
    <label>Issue/Return Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Item Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue/Return Item(s)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Issued_To__c.field-meta.xml
<CustomField>
    <fullName>Issued_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issued To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Issue/Return Item(s)</relationshipLabel>
    <relationshipName>Issue_Return_Item_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/LMS_SearchMembersController.cls
/*--
* @File Name          : lms_SearchMembers.cmp (Aura Component)
* @Summary            : Component to search Members
* @Created On         : 02 Oct 2020
* @Created By         : sapan Khandelwal
* @Controller         : LMS_SearchMembersController
* @Modification Log   : (Name  -  Date  -  Issue  -  Change Summary)
========================================================================
========================================================================
--*/
public class LMS_SearchMembersController {
    @auraEnabled
    public static List<LMS_SearchMembersController.MemberGridCard> searchRecords(List<LMS_SearchService.LMS_FilterCriteria> filterCriteria, Decimal page, Decimal pageSize, String sortCol, String sortDir)
    {
        system.debug('filterCriteria'+filterCriteria);
        List<LMS_SearchMembersController.MemberGridCard> searchMembersList=new List<LMS_SearchMembersController.MemberGridCard>();
        List<User> searchList=new List<User>();
        List<id> userContactIds=new List<id>();
        Map<id,Integer> userItemCount=new Map<id,Integer>();
        
        LMS_SearchService searchObj=new LMS_SearchService(filterCriteria,1,200,'Name','Asc');
        searchObj.objectName=Constants.LMS_USER_OBJECTNAME;
        searchObj.objectFieldSetName=Constants.LMS_USER_SEARCHFIELDSET;
        searchList= searchObj.searchRecords();
        //get total issued Items of user
         for(User u :searchList)
         {
             
          userContactIds.add(u.ContactId);   
         }
        if(userContactIds!=null && !userContactIds.isEmpty())
        {
            
            for(AggregateResult a :[select count(id) totalcount,Issued_To__c  from Library_Issue_Ret_Item__c where Issued_To__c in:userContactIds group by Issued_To__c ]) {  
            Integer count=(Integer)a.get('totalcount');
      		userItemCount.put((Id)a.get('Issued_To__c'),count);
        }
            
        }
         for(User u :searchList)
                {
                    MemberGridCard memb = new MemberGridCard();
                    memb.id = String.valueOf(u.contactId);
                    memb.contact =u.contact;
                    memb.user = u;
                    memb.profilePhotoUrl = memb.user.SmallPhotoUrl;
                    searchMembersList.add(memb);
                    memb.currentIssuedItems=userItemCount.get(u.contactId)==null?0:userItemCount.get(u.contactId);
                }         
        system.debug('searchMembersList'+searchMembersList);
             return searchMembersList;
       
        
             
    } 
     public class MemberGridCard  {
        @AuraEnabled
        public String id{get;set;}
        
        @AuraEnabled
        public Contact contact{get;set;}
        
        @AuraEnabled
        public User user{get;set;}
        
         @AuraEnabled
        public Integer currentIssuedItems{get;set;}
       
         @AuraEnabled
        public String profilePhotoUrl{get;set;}
    }
}