unpackaged/main/default/objects/Library_Issue_Ret_Item__c/Library_Issue_Ret_Item__c.object-meta.xml
<CustomObject>
    <description>This Object is used to issue/return  Library Item(Books/)</description>
    <label>Issue/Return Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Item Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue/Return Item(s)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Library_Item__c.field-meta.xml
<CustomField>
    <fullName>Library_Item__c</fullName>
    <label>Library Item</label>
    <referenceTo>Library_Item__c</referenceTo>
    <relationshipLabel>Issue/Return Item(s)</relationshipLabel>
    <relationshipName>Issue_Return_Item_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Library_Item__c/Library_Item__c.object-meta.xml
<CustomObject>
    <description>This would be used to maintains Books/Magazines/NewsPapers</description>
    <label>Library Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/Constants.cls
/*--
* @File Name          : Constants.cls
* @Summary            : Constant class for all classes,stores label,picklist valuesa and messages
* @Created On         : 02 Oct 2020
* @Created By         : sapan Khandelwal
* @Modification Log   : (Name  -  Date  -  Issue  -  Change Summary)
========================================================================
========================================================================
--*/
public class Constants {
//user Object fields
public static final String LMS_USER_OBJECTNAME='User';
public static final String LMS_USER_SEARCHFIELDSET='LMS_Search_User_Fields';

//Library Item Object fields
public static final String LMS_LIBITEM_OBJECTNAME='Library_Item__c';
public static final String LMS_LBITEM_SEARCHFIELDSET='LMS_LibraryItem_SearchFields';
    
//Library Issue Return Item Object fields
public static String LMS_LIBISSUERETURN_OBJECTNAME='Library_Issue_Ret_Item__c';
public static final String LMS_LIBISSUERETURN_SEARCHFIELDSET='LMS_Search_IssueReturn_Fields';
  
public static final String MEMBER_ISSUEDTHRESHOLD_MESSAGE='Cannot issue item,Maximum count reached for Member';

public static final String MEMBER_SINGLEITEMISSUETHRESHOLD_MESSAGE='Item already issued to Member';
        
    
    
    
}