unpackaged/main/default/objects/Library_Issue_Ret_Item__c/Library_Issue_Ret_Item__c.object-meta.xml
<CustomObject>
    <description>This Object is used to issue/return  Library Item(Books/)</description>
    <label>Issue/Return Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Item Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue/Return Item(s)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Library_Item__c.field-meta.xml
<CustomField>
    <fullName>Library_Item__c</fullName>
    <label>Library Item</label>
    <referenceTo>Library_Item__c</referenceTo>
    <relationshipLabel>Issue/Return Item(s)</relationshipLabel>
    <relationshipName>Issue_Return_Item_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Library_Item__c/Library_Item__c.object-meta.xml
<CustomObject>
    <description>This would be used to maintains Books/Magazines/NewsPapers</description>
    <label>Library Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/LMS_SearchLibItemsController_Test.cls
@isTest
public class LMS_SearchLibItemsController_Test {


 @isTest static void searchLibraryItems()
 {
     //create Library Items
     List<Library_Item__c> itemList=LMS_TestUtility.createLibraryItems(3, true);
     
     //Create Account and Contact
     List<Account> accList=LMS_TestUtility.createAccount(1, true);
	 List<Contact> conList=LMS_TestUtility.createContact(accList[0], 'test', 2, true);
         
     List<Library_Issue_Ret_Item__c> itemIssueList=LMS_TestUtility.createLibrary_Issue_Items(itemList[0], conList[0], 5, true);
     //check itemList
     system.assert(itemIssueList!=null);
     List<LMS_SearchService.LMS_FilterCriteria> filterCriteria =new List<LMS_SearchService.LMS_FilterCriteria> ();
    
     //check getLibraryItems
     List<Sobject> searchRecords1=LMS_SearchLibItemsController.getLibraryItems(filterCriteria);
     
 	 system.assert(searchRecords1.size()>0);
         
 }
    
    
}