unpackaged/main/default/objects/Contact/fields/If_LMS_User__c.field-meta.xml
<CustomField>
    <fullName>If_LMS_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>If LMS User?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/Library_Issue_Ret_Item__c.object-meta.xml
<CustomObject>
    <description>This Object is used to issue/return  Library Item(Books/)</description>
    <label>Issue/Return Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Item Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue/Return Item(s)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Expected_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Return_Date__c</fullName>
    <label>Expected Return Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/is_Issued__c.field-meta.xml
<CustomField>
    <fullName>is_Issued__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This would be checked when status =issued</description>
    <label>is Issued</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Issued_By__c.field-meta.xml
<CustomField>
    <fullName>Issued_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issued By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Issue_Return_Item_s</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Issued_To__c.field-meta.xml
<CustomField>
    <fullName>Issued_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issued To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Issue/Return Item(s)</relationshipLabel>
    <relationshipName>Issue_Return_Item_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Library_Item__c.field-meta.xml
<CustomField>
    <fullName>Library_Item__c</fullName>
    <label>Library Item</label>
    <referenceTo>Library_Item__c</referenceTo>
    <relationshipLabel>Issue/Return Item(s)</relationshipLabel>
    <relationshipName>Issue_Return_Item_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Library_Item__c/Library_Item__c.object-meta.xml
<CustomObject>
    <description>This would be used to maintains Books/Magazines/NewsPapers</description>
    <label>Library Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Library_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Fiction</fullName>
            </value>
            <value>
                <fullName>Programming Languages</fullName>
            </value>
            <value>
                <fullName>Story</fullName>
            </value>
            <value>
                <fullName>Wildlife</fullName>
            </value>
            <value>
                <fullName>Movies</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Library_Item__c/fields/ISBN_No__c.field-meta.xml
<CustomField>
    <fullName>ISBN_No__c</fullName>
    <externalId>true</externalId>
    <label>ISBN No.</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Library_Item__c/fields/Item_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_Price__c</fullName>
    <description>This is per item Price</description>
    <label>Item Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Library_Item__c/fields/Total_Copies__c.field-meta.xml
<CustomField>
    <fullName>Total_Copies__c</fullName>
    <label>Total Copies</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Library_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Book</fullName>
            </value>
            <value>
                <fullName>CD/DVD</fullName>
            </value>
            <value>
                <fullName>Magazines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Library_Item__c/recordTypes/Book.recordType-meta.xml
<RecordType>
    <fullName>Book</fullName>
    <active>true</active>
    <description>This is for Book type Items</description>
    <label>Book</label>
</RecordType>

unpackaged/main/default/objects/Library_Item_Rating__c/Library_Item_Rating__c.object-meta.xml
<CustomObject>
    <description>This would be used to rate the Library Items</description>
    <label>Library Item Rating</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Item Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library Item Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Library_Item_Rating__c/fields/Issued_To__c.field-meta.xml
<CustomField>
    <fullName>Issued_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issued To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Library Item Ratings</relationshipLabel>
    <relationshipName>Item_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Library_Item_Rating__c/fields/Library_Item__c.field-meta.xml
<CustomField>
    <fullName>Library_Item__c</fullName>
    <label>Library Item</label>
    <referenceTo>Library_Item__c</referenceTo>
    <relationshipName>Item_Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Library_Item_Rating__c/fields/Rate_Points__c.field-meta.xml
<CustomField>
    <fullName>Rate_Points__c</fullName>
    <label>Rate Points</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LMS_TestUtility.cls
/*--
* @File Name          : LMS_TestUtility.cls
* @Summary            :  utility class for all test class forcreating data
* @Created On         : 02 Oct 2020
* @Created By         : sapan Khandelwal
* @Modification Log   : (Name  -  Date  -  Issue  -  Change Summary)
========================================================================
========================================================================
--*/
@isTest
public class LMS_TestUtility {
    
     public static List<Library_Item_Rating__c> createRatings(Contact con,Library_Item__c item,Integer noOfrecords,Boolean isInsert)
    {
        List<Library_Item_Rating__c> itemRating=new List<Library_Item_Rating__c>();
        
        for(Integer i=0;i<noOfrecords;i++)
        {
            itemRating.add(new Library_Item_Rating__c( Library_Item__c=item.id,Issued_To__c=con.id,Rate_Points__c='5'));
            
            
            
        }
        if(isInsert)
        {
            insert itemRating;
        }    
        return itemRating;
    }
    public static List<Library_Item__c> createLibraryItems(Integer noOfrecords,boolean isInsert)
    {
        List<Library_Item__c> itemList=new List<Library_Item__c>();
        
        for(Integer i=0;i<noOfrecords;i++)
        {
            itemList.add(new Library_Item__c( name='Test Book'+i,ISBN_No__c='123456789012'+i,Type__c='Book',Publishing_Date__c=System.Today()-i,Total_Copies__c=10,category__c='Fiction',Item_Price__c=100));
            
            
            
        }
        if(isInsert)
        {
            insert itemList;
        }    
        return itemList;
    }
    public static List<Library_Issue_Ret_Item__c> createLibrary_Issue_Items(Library_Item__c item,Contact con,Integer noOfrecords,boolean isInsert)
    {
        List<Library_Issue_Ret_Item__c> newList=new List<Library_Issue_Ret_Item__c>();
        
        for(Integer i=0;i<noOfrecords;i++)
        {
            
            Library_Issue_Ret_Item__c newRecord=new Library_Issue_Ret_Item__c();
            newRecord.is_Issued__c=true;
            newRecord.Issue_Date__c=system.today();
            newRecord.Library_Item__c=item.Id;
            newRecord.Issued_To__c=con.id;
            newRecord.Status__c='Issued';
            
            newRecord.Issued_By__c=Userinfo.getUserId();
            
            newRecord.Expected_Return_Date__c=system.today()+3;
            newList.add(newRecord);
            
            
            
        }
        if(isInsert)
        {
            insert newList;
        }    
        return newList;
    }
      public static List<Library_Issue_Ret_Item__c> createLibrary_Issue_Items(List<Library_Item__c> item,Contact con,Integer noOfrecords,boolean isInsert)
    {
        List<Library_Issue_Ret_Item__c> newList=new List<Library_Issue_Ret_Item__c>();
        
        for(Integer i=0;i<noOfrecords;i++)
        {
            
            Library_Issue_Ret_Item__c newRecord=new Library_Issue_Ret_Item__c();
            newRecord.is_Issued__c=true;
            newRecord.Issue_Date__c=system.today();
            newRecord.Library_Item__c=item[i].Id;
            newRecord.Issued_To__c=con.id;
            newRecord.Status__c='Issued';
            
            newRecord.Issued_By__c=Userinfo.getUserId();
            
            newRecord.Expected_Return_Date__c=system.today()+3;
            newList.add(newRecord);
            
            
            
        }
        if(isInsert)
        {
            insert newList;
        }    
        return newList;
    }
    public static List<Account> createAccount(Integer noOfrecords,boolean isInsert)
    {
        List<Account> accList=new List<Account>();
        for(Integer i=0;i<noOfrecords;i++)
        {
            account acc= new Account();
            acc.BillingStreet='Test'+i;
            acc.BillingCity='New York City';
            acc.BillingCountry='United States';
            acc.BillingPostalCode='10021';
            acc.BillingState='New York';
            acc.Name='Testing'+i;
            accList.add(acc);
            
        } 
        if(isInsert)
        {
            insert accList;
        }
        return accList;
    }
    public static List<User> createCommunityUser(String userName,Profile p,Contact con,Integer noOfrecords,boolean isInsert)
    {
        List<User> userList=new List<User>();
        for(Integer i=0;i<noOfrecords;i++)
        {
            
            String str = string.valueof(Math.abs(Crypto.getRandomLong()));
            String randomNumber = str.substring(0, 5);
            User us= new User(alias = 'test123', email=userName+i+'@noemail.com',
                              emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                              localesidkey='en_US', profileid = p.Id, country='United States',IsActive =true,contactId=con.id,
                              timezonesidkey='America/Los_Angeles', username=userName+i+randomNumber+'@noemail.com');
            userList.add(us);
            
        } 
        if(isInsert)
        {
            insert userList;
        }
        return userList;
    }    
    public static List<User> createUser(String userName,Profile p,UserRole r,Integer noOfrecords,boolean isInsert)
    {
        List<User> userList=new List<User>();
        for(Integer i=0;i<noOfrecords;i++)
        {
            String str = string.valueof(Math.abs(Crypto.getRandomLong()));
            String randomNumber = str.substring(0, 5);
            
            User us= new User(alias = 'test123', email=userName+'_'+i+'@noemail.com',
                              emailencodingkey='UTF-8', lastname='TestingTOD'+i, languagelocalekey='en_US',
                              localesidkey='en_US', profileid = p.id, country='United States',IsActive =true,
                              timezonesidkey='America/Los_Angeles',userRoleid=r.id, username=userName+i+randomNumber+'@noemail.com');
            userList.add(us);
            
        } 
        if(isInsert)
        {
            insert userList;
        }
        return userList;
    }
    public static List<Contact> createContact(Account acc,String lastName,Integer noOfrecords,boolean isInsert)
    {
        List<Contact> contactList=new List<Contact>();
        for(Integer i=0;i<noOfrecords;i++)
        {
            Contact con=new Contact();
            con.Firstname='Test'+i;
            con.LastName=lastName+i;
            con.AccountId=acc.Id;
            con.MailingStreet='Test'+i;
            con.MailingCity='New York City';
            con.MailingCountry='United States';
            con.MailingPostalCode='10021';
            con.MailingState='New York';
            con.Email=con.Firstname+'@tod.com';
            con.If_LMS_User__c=true;
            contactList.add(con);
            
        } 
        if(isInsert)
        {
            insert contactList;
        }
        return contactList;
    }
    
    
}