unpackaged/main/default/objects/Library_Item__c/Library_Item__c.object-meta.xml
<CustomObject>
    <description>This would be used to maintains Books/Magazines/NewsPapers</description>
    <label>Library Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Library_Item__c/fields/Avg_Rating__c.field-meta.xml
<CustomField>
    <fullName>Avg_Rating__c</fullName>
    <label>Avg Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Library_Item__c/fields/Ratings__c.field-meta.xml
<CustomField>
    <fullName>Ratings__c</fullName>
    <formula>IMAGE(
IF((Avg_Rating__c) = 0, &quot;/img/samples/stars_000.gif&quot;,
IF((Avg_Rating__c) = 1, &quot;/img/samples/stars_100.gif&quot;,
IF((Avg_Rating__c) = 2, &quot;/img/samples/stars_200.gif&quot;,
IF((Avg_Rating__c) = 3, &quot;/img/samples/stars_300.gif&quot;,
IF((Avg_Rating__c) = 4, &quot;/img/samples/stars_400.gif&quot;,
IF((Avg_Rating__c) = 5, &quot;/img/samples/stars_500.gif&quot;,
&quot;/img/samples/stars_000.gif&quot;
)))))),
&#39;Rating Level&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ratings</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Library_Item_Rating__c/Library_Item_Rating__c.object-meta.xml
<CustomObject>
    <description>This would be used to rate the Library Items</description>
    <label>Library Item Rating</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Item Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library Item Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Library_Item_Rating__c/fields/Library_Item__c.field-meta.xml
<CustomField>
    <fullName>Library_Item__c</fullName>
    <label>Library Item</label>
    <referenceTo>Library_Item__c</referenceTo>
    <relationshipName>Item_Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Library_Item_Rating__c/fields/Ratings__c.field-meta.xml
<CustomField>
    <fullName>Ratings__c</fullName>
    <formula>VALUE(Text(Rate_Points__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ratings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/LMS_ItemRating_TriggerHelper.cls
/*--
* @File Name          : LMS_ItemRating_TriggerHelper.cls
* @Summary            : handler for Trigger LMS_ItemRating_TriggerHandler
* @Created On         : 09 Oct 2020
* @Created By         : sapan Khandelwal
* @Modification Log   : (Name  -  Date  -  Issue  -  Change Summary)
========================================================================
sapan 9 Oct 2020			 added method rollUpRatingOnItem to rollup rating 
========================================================================*/

public class LMS_ItemRating_TriggerHelper {
    
    
    //this method rolls up rating on Library_Item,could hve been done from rollup but avg cannot be calculated on master
    public static void rollUpRatingOnItem(List<Library_Item_Rating__c> newList)
    {
        List<AggregateResult> result=new  List<AggregateResult>();
        Map<id,Library_Item__c> libItemMap=new Map<Id,Library_Item__c>();
        for(Library_Item_Rating__c ir: newList)
        {
            if(!libItemMap.containsKey(ir.Library_Item__c))
            {
                libItemMap.put(ir.Library_Item__c,new Library_Item__c(id=ir.Library_Item__c,Avg_Rating__c=0)); 
            }   
            
        }
        result=[select Library_Item__c,avg(Ratings__c) AVGRatings
                from Library_Item_Rating__c
                where Library_Item__c in:libItemMap.keySet() group by Library_Item__c];
        for(AggregateResult a : Result) {  
            Decimal rating=(Decimal)a.get('AVGRatings');
            if(rating==null){rating=0;}
            libItemMap.get((Id)a.get('Library_Item__c')).Avg_Rating__c=rating.setScale(0);
        }
        if(libItemMap!=null && !libItemMap.isEmpty())
        {
            update libItemMap.values();
            
        }
    }  
}