unpackaged/main/default/objects/Library_General_Settings__c/Library_General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This would be used to store the general settings of Library as per Profiles/user</description>
    <label>Library General Settings</label>
</CustomObject>

unpackaged/main/default/objects/Library_General_Settings__c/fields/Item_Issue_Limit__c.field-meta.xml
<CustomField>
    <fullName>Item_Issue_Limit__c</fullName>
    <label>Item Issue Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/Library_Issue_Ret_Item__c.object-meta.xml
<CustomObject>
    <description>This Object is used to issue/return  Library Item(Books/)</description>
    <label>Issue/Return Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Item Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue/Return Item(s)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Issued_To__c.field-meta.xml
<CustomField>
    <fullName>Issued_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Issued To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Issue/Return Item(s)</relationshipLabel>
    <relationshipName>Issue_Return_Item_s</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Library_Item__c.field-meta.xml
<CustomField>
    <fullName>Library_Item__c</fullName>
    <label>Library Item</label>
    <referenceTo>Library_Item__c</referenceTo>
    <relationshipLabel>Issue/Return Item(s)</relationshipLabel>
    <relationshipName>Issue_Return_Item_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Library_Issue_Ret_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Library_Item__c/Library_Item__c.object-meta.xml
<CustomObject>
    <description>This would be used to maintains Books/Magazines/NewsPapers</description>
    <label>Library Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/LMS_IssueRet_TriggerHelper.cls
/*--
* @File Name          : LMS_IssueRet_TriggerHelper
* @Summary            : Helper for LMS_IssueRet_TriggerHandler
* @Created On         : 01 Oct 2020
* @Created By         : sapan Khandelwal
* @Modification Log   : (Name  -  Date  -  Issue  -  Change Summary)
========================================================================
========================================================================
--*/
public without sharing class  LMS_IssueRet_TriggerHelper {
    
    public static  Boolean  isRecursive=false;
    
    //used to check total item issued by user and display error if maximum count reached
    public static void checkIssuedItemCount(List<Library_Issue_Ret_Item__c> newList,Map<Id, sObject> oldMapSObject)
    {
        Map<id,Library_Issue_Ret_Item__c> oldMap=null;
        
        
        Library_General_Settings__c  triggerSettings= Library_General_Settings__c.getInstance();
        Integer totalItemLimit=(Integer)triggerSettings.Item_Issue_Limit__c;
        Map<String,Integer> membertotalitemCount=new Map<String,Integer>();//used to check total item issued by a member
        Map<Id,Contact> contactMap=null;//used to check total item issued by a member
        
        Set<Id> itemList=new Set<id>();//
        Set<Id> contactList=new set<id>();//
        
        Map<String,Integer> memberitemConcatMap=new Map<String,Integer>();//used to check count os single item issued by a member
        
        List<Library_Issue_Ret_Item__c> filterList=new List<Library_Issue_Ret_Item__c>();
        
        if(oldMapSObject!=null)
        {
            oldMap=new Map<id,Library_Issue_Ret_Item__c>();
            for(Id key : oldMapSObject.keySet())
            {
                oldMap.put(key, (Library_Issue_Ret_Item__c)oldMapSObject.get(key));
            }
        }
           //get all the new item issued in Map with contacid and library Item
     
        for(Library_Issue_Ret_Item__c issueItem: newList)
        {
            if(issueItem.Status__c=='Issued' && (oldMap==null ||oldMap.get(issueItem.id).status__c!=issueItem.Status__c))
            {
                filterList.add(issueItem);
                itemList.add(issueItem.Library_Item__c);
                contactList.add(issueItem.Issued_To__c);
            }  
            
        }
        if(!filterList.isEmpty())
        {
            List<Library_Issue_Ret_Item__c> existingList=  [select   id,library_Item__c,Issued_To__c  from Library_Issue_Ret_Item__c 
                                                            where Issued_To__c in :contactList 
                                                            and status__c='Issued'];
            
            contactMap=  new Map<id,contact>([select id,name from Contact where id in:contactList]);
            
            if(existingList==null || existingList.isEmpty()){
                
                existingList=new List<Library_Issue_Ret_Item__c>();
                
            }
            existingList.addAll(filterList);
            system.debug('existingList'+existingList);
            //check the existing issued Item
            if(membertotalitemCount!=null && membertotalitemCount.isEmpty())
            {
                for(Library_Issue_Ret_Item__c issueItem:existingList  )
                {
                    if(!membertotalitemCount.containsKey(issueItem.Issued_To__c))
                    {
                        membertotalitemCount.put(issueItem.Issued_To__c,0);   
                    }
                    membertotalitemCount.put(issueItem.Issued_To__c , membertotalitemCount.get(issueItem.Issued_To__c)+1);
                    //now create a concat key
                    
                    String key=issueItem.Issued_To__c+'-'+issueItem.Library_Item__c;
                    if(!memberitemConcatMap.containsKey(key))
                    {
                        memberitemConcatMap.put(key,0);   
                    }
                    memberitemConcatMap.put(key , memberitemConcatMap.get(key)+1);
                    
                }
                
                
                system.debug('membertotalitemCount'+membertotalitemCount);
                system.debug('memberitemConcatMap'+memberitemConcatMap);
                
                //now loop filteredlist and check for count and throw error
                for(Library_Issue_Ret_Item__c issueItem:filterList)
                {
                    String key=issueItem.Issued_To__c+'-'+issueItem.Library_Item__c;
                    if(memberitemConcatMap.containsKey(key) && memberitemConcatMap.get(key)>1)
                    {
                        issueItem.addError(issueItem.Library_Item_Name__c+' '+ Constants.MEMBER_SINGLEITEMISSUETHRESHOLD_MESSAGE+' '+(contactMap.get(issueItem.Issued_To__c)!=null?contactMap.get(issueItem.Issued_To__c).Name:'')); 
                        
                        
                    }
                    if(membertotalitemCount.containsKey(issueItem.Issued_To__c) && membertotalitemCount.get(issueItem.Issued_To__c)>totalItemLimit)
                    {
                        issueItem.addError(Constants.MEMBER_ISSUEDTHRESHOLD_MESSAGE+' '+contactMap.get(issueItem.Issued_To__c).Name); 
                        
                        
                    }
                    
                }
            }
            
        }
        isRecursive=true;
    }
    
    
}